//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charge_rate
    {
        public int charge_id { get; set; }
        public Nullable<int> sp_id { get; set; }
        public Nullable<int> sptype_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string description { get; set; }
    }
}
