//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBServiceProviderEntities : DbContext
    {
        public DBServiceProviderEntities()
            : base("name=DBServiceProviderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminSp_plan> AdminSp_plan { get; set; }
        public DbSet<Area_master> Area_master { get; set; }
        public DbSet<Charge_rate> Charge_rate { get; set; }
        public DbSet<City_master> City_master { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<Plan_Enroll> Plan_Enroll { get; set; }
        public DbSet<Plan_maintanance> Plan_maintanance { get; set; }
        public DbSet<Serviceprovider_regis> Serviceprovider_regis { get; set; }
        public DbSet<ServiceproviderType> ServiceproviderTypes { get; set; }
        public DbSet<Sp_plan_Enroll> Sp_plan_Enroll { get; set; }
        public DbSet<Tbl_plan> Tbl_plan { get; set; }
        public DbSet<tblAdminLogin> tblAdminLogins { get; set; }
        public DbSet<User_complaint> User_complaint { get; set; }
        public DbSet<User_regis> User_regis { get; set; }
        public DbSet<user_request> user_request { get; set; }
        public DbSet<User_request_type> User_request_type { get; set; }
        public DbSet<User_review> User_review { get; set; }
    }
}
