//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payment_id { get; set; }
        public Nullable<int> userreq_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> extra_amount { get; set; }
        public string description { get; set; }
        public Nullable<decimal> totamount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string payment_mode { get; set; }
        public string status { get; set; }
    }
}
