//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Enroll
    {
        public int planenroll_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> sp_id { get; set; }
        public string plan_status { get; set; }
        public Nullable<int> plan_id { get; set; }
        public Nullable<System.DateTime> plan_date { get; set; }
        public Nullable<System.DateTime> planend_date { get; set; }
        public string description { get; set; }
    }
}
