//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serviceprovider_regis
    {
        public int sp_id { get; set; }
        public string sp_fname { get; set; }
        public string sp_lname { get; set; }
        public string sp_logo { get; set; }
        public string sp_gender { get; set; }
        public string sp_email { get; set; }
        public Nullable<decimal> sp_mobile { get; set; }
        public Nullable<int> sptype_id { get; set; }
        public Nullable<System.DateTime> spregis_date { get; set; }
        public string sp_status { get; set; }
        public string address { get; set; }
        public string password { get; set; }
    }
}
