//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sp_plan_Enroll
    {
        public int sp_plan_id { get; set; }
        public Nullable<int> sub_id { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> Otpnumber { get; set; }
        public Nullable<int> sp_id { get; set; }
        public string status { get; set; }
    }
}
