//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_review
    {
        public int review_id { get; set; }
        public Nullable<int> userreq_id { get; set; }
        public Nullable<int> sp_id { get; set; }
        public string review_desc { get; set; }
    }
}
