//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_regis
    {
        public int user_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public Nullable<decimal> mobile { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string address { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> area_id { get; set; }
        public string password { get; set; }
        public string user_img { get; set; }
        public string status { get; set; }
    }
}
